import { Router } from "express";
import { workflowManager } from "../services/brainCloud/WorkflowManager.ts";
import { logger } from "../src/utils/logger.js";

const router = Router();

router.get("/", async (req, res) => {
  try {
    const { enabled, createdBy, triggerType } = req.query;

    const workflows = await workflowManager.listWorkflows({
      enabled:
        enabled !== undefined ? String(enabled).toLowerCase() === "true" : undefined,
      createdBy: createdBy ? String(createdBy) : undefined,
      triggerType: triggerType ? String(triggerType) : undefined,
    });

    res.json({
      success: true,
      workflows,
      total: workflows.length,
    });
  } catch (error) {
    logger.error("[Workflows API] Failed to list workflows", { error });
    res.status(500).json({
      success: false,
      error: error instanceof Error ? error.message : "Internal server error",
    });
  }
});

router.get("/system/health", async (req, res) => {
  try {
    const health = workflowManager.getHealth();
    res.json({
      success: true,
      health,
    });
  } catch (error) {
    logger.error("[Workflows API] Failed to get workflow health", { error });
    res.status(500).json({
      success: false,
      error: error instanceof Error ? error.message : "Internal server error",
    });
  }
});

router.get("/:id", async (req, res) => {
  try {
    const workflow = await workflowManager.getWorkflow(req.params.id);

    if (!workflow) {
      return res.status(404).json({
        success: false,
        error: "Workflow not found",
      });
    }

    res.json({
      success: true,
      workflow,
    });
  } catch (error) {
    logger.error("[Workflows API] Failed to retrieve workflow", {
      error,
      workflowId: req.params.id,
    });
    res.status(500).json({
      success: false,
      error: error instanceof Error ? error.message : "Internal server error",
    });
  }
});

router.post("/", async (req, res) => {
  try {
    const { name, description, enabled, trigger, actions, settings, source } =
      req.body || {};

    if (!name || !trigger || !actions) {
      return res.status(400).json({
        success: false,
        error: "Missing required fields: name, trigger, actions",
      });
    }

    if (!Array.isArray(actions) || actions.length === 0) {
      return res.status(400).json({
        success: false,
        error: "Workflow must contain at least one action",
      });
    }

    const createdBy = req.user?.id ?? "system";

    const id = await workflowManager.createWorkflow({
      id: "", // will be generated by manager
      name,
      description,
      enabled: enabled !== undefined ? Boolean(enabled) : true,
      trigger,
      actions,
      settings,
      source: source ?? "ui",
      createdBy,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    });

    res.status(201).json({
      success: true,
      id,
      message: "Workflow created successfully",
    });
  } catch (error) {
    logger.error("[Workflows API] Failed to create workflow", { error });
    res.status(500).json({
      success: false,
      error: error instanceof Error ? error.message : "Internal server error",
    });
  }
});

router.patch("/:id", async (req, res) => {
  try {
    const updates = req.body ?? {};
    await workflowManager.updateWorkflow(req.params.id, updates);

    res.json({
      success: true,
      message: "Workflow updated successfully",
    });
  } catch (error) {
    logger.error("[Workflows API] Failed to update workflow", {
      error,
      workflowId: req.params.id,
    });
    res.status(500).json({
      success: false,
      error: error instanceof Error ? error.message : "Internal server error",
    });
  }
});

router.delete("/:id", async (req, res) => {
  try {
    await workflowManager.deleteWorkflow(req.params.id);
    res.json({
      success: true,
      message: "Workflow deleted successfully",
    });
  } catch (error) {
    logger.error("[Workflows API] Failed to delete workflow", {
      error,
      workflowId: req.params.id,
    });
    res.status(500).json({
      success: false,
      error: error instanceof Error ? error.message : "Internal server error",
    });
  }
});

router.post("/:id/execute", async (req, res) => {
  try {
    const context = req.body?.context ?? {};
    const execution = await workflowManager.executeWorkflow(req.params.id, {
      ...context,
      userId: req.user?.id ?? context?.userId,
    });

    res.json({
      success: true,
      execution,
    });
  } catch (error) {
    logger.error("[Workflows API] Failed to execute workflow", {
      error,
      workflowId: req.params.id,
    });
    res.status(500).json({
      success: false,
      error: error instanceof Error ? error.message : "Internal server error",
    });
  }
});

router.get("/:id/executions", async (req, res) => {
  try {
    const executions = await workflowManager.listExecutions(req.params.id);
    res.json({
      success: true,
      executions,
      total: executions.length,
    });
  } catch (error) {
    logger.error("[Workflows API] Failed to list executions", {
      error,
      workflowId: req.params.id,
    });
    res.status(500).json({
      success: false,
      error: error instanceof Error ? error.message : "Internal server error",
    });
  }
});

router.get("/:id/stats", async (req, res) => {
  try {
    const stats = await workflowManager.getWorkflowStats(req.params.id);
    res.json({
      success: true,
      stats,
    });
  } catch (error) {
    logger.error("[Workflows API] Failed to get workflow stats", {
      error,
      workflowId: req.params.id,
    });
    res.status(500).json({
      success: false,
      error: error instanceof Error ? error.message : "Internal server error",
    });
  }
});

export default router;
